### PR TITLE
Update net.c

### PR DESCRIPTION
**Pull request by fennectech**
Added all available mount points in storagemgr https://github.com/CelesteBlue-dev/PSVita-StorageMgr

These mount points will appear in the ftp directory if present now :)
ux0
xmc0
imc0
uma0
grw0
ur0

### CODE REVIEW

**Comment by fennectech** [comment]
Is this thing dead?

**Comment by devnoname120** [comment]
No, I just never got around to test whether this causes any issues if those mount points are not available.

**Comment by fennectech** [comment]
If the mount points aren't available they simply dont appear.

**Comment by fennectech** [comment]
Could you toss me a build?  I'm unable to build this code base anymore with the current SDK :/.

**Comment by fennectech** [comment]
I mean. I was able to build it before.  But in the year or so thats gone since then the vita SDK has changed too much that it fails to build.  Errors in linking the executable.

**Pull request merged**
